### ISSUE TITLE
error: externally-managed-environment

### ISSUE THREAD

**Issue by Fat-bear** [Vozec/CTFileScan-WEB#1]
> [web 5/8] RUN     python -m pip install -r requirements.txt ;:
3.026 error: externally-managed-environment
3.026
3.026 × This environment is externally managed
3.026 ╰─> To install Python packages system-wide, try apt install
3.026     python3-xyz, where xyz is the package you are trying to
3.026     install.
3.026
3.026     If you wish to install a non-Debian-packaged Python package,
3.026     create a virtual environment using python3 -m venv path/to/venv.
3.026     Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
3.026     sure you have python3-full installed.
3.026
3.026     If you wish to install a non-Debian packaged Python application,
3.026     it may be easiest to use pipx install xyz, which will manage a
3.026     virtual environment for you. Make sure you have pipx installed.
3.026
3.026     See /usr/share/doc/python3.12/README.venv for more information.
3.026
3.026 note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
3.026 hint: See PEP 668 for the detailed specification.
------
failed to solve: process "/bin/sh -c python -m pip install -r requirements.txt ;" did not complete successfully: exit code: 1

**Comment by 20urc3** [comment]
@Fat-bear  this has *nothing* to do with CTFlagger, you literally got the solution in the output: `You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.`
